### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by jouishi** [jouishi/protospace-39413#1]
#URL
https://protospace-39413.onrender.com/

**Comment by motomuun** [comment]
@jouishi さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**プロトタイプ編集機能**

- [x] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
空のフォームがある状態で「保存する」ボタンを押すと、入力済みのフォームまで中身が消えてしまいます。そのページに留まった場合でも、入力済みの項目（画像以外）は消えないように修正をお願いします。

**コメント機能**

- [x] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
フォームが空のままでコメントの「送信する」ボタンを押すと、エラーページに遷移します。投稿できずにそのページに留まるように修正をお願いします。

**ユーザー詳細機能**

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
「ユーザー名」と表示されているところに正しいユーザー名が表示されるように修正をお願いします。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by jouishi** [comment]
訂正箇所を修正したので再度確認お願いします。

**Comment by shodai-ito** [comment]
@jouishi さん、ご提出ありがとうございます‼︎
上記指摘内容の修正が確認できました。
引き続き修正いただきたい箇所もございましたので、以下のご確認をお願いします！

[修正依頼箇所]
- [x] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
入力内容に空欄がある状態で編集を試みると、その他の項目も空欄になってしまいます。
そこからもう一度編集を試みるとエラーになってしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by jouishi** [comment]
再度訂正箇所を修正したので再度確認お願いします。

**Comment by shodai-ito** [comment]
@jouishi さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
